//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A5_Client_Sandy.SS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SS.SandyServiceInterface")]
    public interface SandyServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/readTable", ReplyAction="http://tempuri.org/SandyServiceInterface/readTableResponse")]
        System.Collections.Generic.List<string> readTable(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/readTable", ReplyAction="http://tempuri.org/SandyServiceInterface/readTableResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> readTableAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/listPurchases", ReplyAction="http://tempuri.org/SandyServiceInterface/listPurchasesResponse")]
        System.Collections.Generic.List<string> listPurchases(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/listPurchases", ReplyAction="http://tempuri.org/SandyServiceInterface/listPurchasesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> listPurchasesAsync(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/runSelect", ReplyAction="http://tempuri.org/SandyServiceInterface/runSelectResponse")]
        System.Collections.Generic.List<string> runSelect(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/runSelect", ReplyAction="http://tempuri.org/SandyServiceInterface/runSelectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> runSelectAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/placeOrder", ReplyAction="http://tempuri.org/SandyServiceInterface/placeOrderResponse")]
        void placeOrder(string cid, System.Collections.Generic.List<int> pids, System.Collections.Generic.List<int> quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SandyServiceInterface/placeOrder", ReplyAction="http://tempuri.org/SandyServiceInterface/placeOrderResponse")]
        System.Threading.Tasks.Task placeOrderAsync(string cid, System.Collections.Generic.List<int> pids, System.Collections.Generic.List<int> quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SandyServiceInterfaceChannel : A5_Client_Sandy.SS.SandyServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SandyServiceInterfaceClient : System.ServiceModel.ClientBase<A5_Client_Sandy.SS.SandyServiceInterface>, A5_Client_Sandy.SS.SandyServiceInterface {
        
        public SandyServiceInterfaceClient() {
        }
        
        public SandyServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SandyServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SandyServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SandyServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> readTable(string s) {
            return base.Channel.readTable(s);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> readTableAsync(string s) {
            return base.Channel.readTableAsync(s);
        }
        
        public System.Collections.Generic.List<string> listPurchases(string cid) {
            return base.Channel.listPurchases(cid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> listPurchasesAsync(string cid) {
            return base.Channel.listPurchasesAsync(cid);
        }
        
        public System.Collections.Generic.List<string> runSelect(string sql) {
            return base.Channel.runSelect(sql);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> runSelectAsync(string sql) {
            return base.Channel.runSelectAsync(sql);
        }
        
        public void placeOrder(string cid, System.Collections.Generic.List<int> pids, System.Collections.Generic.List<int> quantity) {
            base.Channel.placeOrder(cid, pids, quantity);
        }
        
        public System.Threading.Tasks.Task placeOrderAsync(string cid, System.Collections.Generic.List<int> pids, System.Collections.Generic.List<int> quantity) {
            return base.Channel.placeOrderAsync(cid, pids, quantity);
        }
    }
}
